"""
CUSTOS Scheduling Schemas Init
"""

from app.scheduling.schemas.timetable import (
    DayOfWeek,
    TimetableCreate,
    TimetableUpdate,
    TimetableResponse,
    TimetableWithEntries,
    TimetableEntryCreate,
    TimetableEntryBulkCreate,
    TimetableEntryUpdate,
    TimetableEntryResponse,
    TimetableEntryWithDetails,
    PeriodSlot,
    DaySchedule,
    ClassTimetableView,
    TeacherTimetableView,
    TimetableConflict,
    TimetableValidationResult,
    TimetableStats,
)

from app.scheduling.schemas.schedule import (
    ScheduleEntryStatus,
    CalendarDayType,
    CalendarDayCreate,
    CalendarDayBulkCreate,
    CalendarDayUpdate,
    CalendarDayResponse,
    ScheduleEntryCreate,
    ScheduleEntryUpdate,
    ScheduleEntryResponse,
    ScheduleEntryWithDetails,
    GenerateScheduleRequest,
    GenerateScheduleResult,
    DailyPeriodSlot,
    DailySchedule,
    ClassScheduleView,
    TeacherScheduleView,
    StudentScheduleView,
    ScheduleStats,
)

__all__ = [
    # Timetable
    "DayOfWeek",
    "TimetableCreate",
    "TimetableUpdate",
    "TimetableResponse",
    "TimetableWithEntries",
    "TimetableEntryCreate",
    "TimetableEntryBulkCreate",
    "TimetableEntryUpdate",
    "TimetableEntryResponse",
    "TimetableEntryWithDetails",
    "PeriodSlot",
    "DaySchedule",
    "ClassTimetableView",
    "TeacherTimetableView",
    "TimetableConflict",
    "TimetableValidationResult",
    "TimetableStats",
    # Schedule
    "ScheduleEntryStatus",
    "CalendarDayType",
    "CalendarDayCreate",
    "CalendarDayBulkCreate",
    "CalendarDayUpdate",
    "CalendarDayResponse",
    "ScheduleEntryCreate",
    "ScheduleEntryUpdate",
    "ScheduleEntryResponse",
    "ScheduleEntryWithDetails",
    "GenerateScheduleRequest",
    "GenerateScheduleResult",
    "DailyPeriodSlot",
    "DailySchedule",
    "ClassScheduleView",
    "TeacherScheduleView",
    "StudentScheduleView",
    "ScheduleStats",
]
