"""
CUSTOS Fee Extension Models

Fee challans, fines, and late payment tracking.
"""

from datetime import datetime, date
from decimal import Decimal
from enum import Enum
from typing import Optional, List
from uuid import UUID

from sqlalchemy import (
    String, Text, Integer, Float, Numeric, Boolean, Date, DateTime,
    ForeignKey, UniqueConstraint, Index, JSON
)
from sqlalchemy import Enum as SQLEnum
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.base_model import TenantBaseModel


# ============================================
# Enums
# ============================================

class ChallanStatus(str, Enum):
    """Challan status."""
    GENERATED = "generated"
    DOWNLOADED = "downloaded"
    USED = "used"
    EXPIRED = "expired"
    CANCELLED = "cancelled"


class FineType(str, Enum):
    """Types of fines."""
    LATE_FEE = "late_fee"
    LIBRARY = "library"
    ID_CARD = "id_card"
    LAB_DAMAGE = "lab_damage"
    HOSTEL = "hostel"
    EXAMINATION = "examination"
    DISCIPLINARY = "disciplinary"
    OTHER = "other"


class FineStatus(str, Enum):
    """Fine status."""
    PENDING = "pending"
    PAID = "paid"
    WAIVED = "waived"
    PARTIAL = "partial"


# ============================================
# Fee Challan
# ============================================

class FeeChallan(TenantBaseModel):
    """
    Fee Challan for offline payment.
    
    Allows students to pay at bank counters.
    """
    __tablename__ = "fee_challans"
    __table_args__ = (
        UniqueConstraint(
            "tenant_id", "challan_number",
            name="uq_fee_challan_number"
        ),
        Index("ix_challan_student", "tenant_id", "student_id"),
        Index("ix_challan_status", "tenant_id", "status"),
        {"extend_existing": True},
    )
    
    # Challan identification
    challan_number: Mapped[str] = mapped_column(String(50))
    barcode: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    
    # Student
    student_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
    )
    student_name: Mapped[str] = mapped_column(String(200))
    enrollment_number: Mapped[str] = mapped_column(String(50))
    
    # Class/Academic context
    class_id: Mapped[Optional[UUID]] = mapped_column(
        PGUUID(as_uuid=True), nullable=True
    )
    class_name: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    academic_year_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("academic_years.id", ondelete="CASCADE"),
    )
    
    # Invoice reference
    invoice_id: Mapped[Optional[UUID]] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("fee_invoices.id", ondelete="SET NULL"),
        nullable=True,
    )
    
    # Amount details
    fee_components: Mapped[Optional[List[dict]]] = mapped_column(JSON, nullable=True)
    subtotal: Mapped[Decimal] = mapped_column(Numeric(12, 2))
    fine_amount: Mapped[Decimal] = mapped_column(Numeric(12, 2), default=Decimal("0.00"))
    discount_amount: Mapped[Decimal] = mapped_column(Numeric(12, 2), default=Decimal("0.00"))
    total_amount: Mapped[Decimal] = mapped_column(Numeric(12, 2))
    
    # Validity
    issue_date: Mapped[date] = mapped_column(Date)
    valid_from: Mapped[date] = mapped_column(Date)
    valid_until: Mapped[date] = mapped_column(Date)
    
    # Bank details
    bank_name: Mapped[Optional[str]] = mapped_column(String(200), nullable=True)
    bank_account: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    bank_ifsc: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)
    
    # Status
    status: Mapped[ChallanStatus] = mapped_column(
        SQLEnum(ChallanStatus, name="challan_status_enum"),
        default=ChallanStatus.GENERATED
    )
    
    # Download tracking
    download_count: Mapped[int] = mapped_column(Integer, default=0)
    last_downloaded_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    
    # Usage
    used_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    payment_id: Mapped[Optional[UUID]] = mapped_column(
        PGUUID(as_uuid=True), nullable=True
    )
    
    # PDF
    pdf_url: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)
    
    # Generated by
    generated_by: Mapped[Optional[UUID]] = mapped_column(
        PGUUID(as_uuid=True), nullable=True
    )


# ============================================
# Late Fee Rule
# ============================================

class LateFeeRule(TenantBaseModel):
    """
    Late fee calculation rules.
    
    Defines how late fees are calculated for overdue payments.
    """
    __tablename__ = "late_fee_rules"
    __table_args__ = (
        Index("ix_late_fee_rule", "tenant_id", "is_active"),
        {"extend_existing": True},
    )
    
    name: Mapped[str] = mapped_column(String(100))
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    
    # Applicable to
    fee_component_id: Mapped[Optional[UUID]] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("fee_components.id", ondelete="CASCADE"),
        nullable=True,
    )  # If null, applies to all
    class_id: Mapped[Optional[UUID]] = mapped_column(
        PGUUID(as_uuid=True), nullable=True
    )  # If null, applies to all classes
    
    # Calculation method
    is_percentage: Mapped[bool] = mapped_column(Boolean, default=True)
    rate: Mapped[Decimal] = mapped_column(Numeric(10, 2))  # Rate per period
    rate_period: Mapped[str] = mapped_column(String(20), default="day")  # day, week, month
    
    # Limits
    max_amount: Mapped[Optional[Decimal]] = mapped_column(Numeric(12, 2), nullable=True)
    max_percentage: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    
    # Grace period
    grace_days: Mapped[int] = mapped_column(Integer, default=0)
    
    # Caps
    cap_at_original: Mapped[bool] = mapped_column(Boolean, default=False)  # Don't exceed original amount
    
    # Status
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    effective_from: Mapped[date] = mapped_column(Date)
    effective_until: Mapped[Optional[date]] = mapped_column(Date, nullable=True)


# ============================================
# Fine
# ============================================

class Fine(TenantBaseModel):
    """
    Student fine record.
    
    Tracks various fines imposed on students.
    """
    __tablename__ = "fines"
    __table_args__ = (
        Index("ix_fine_student", "tenant_id", "student_id"),
        Index("ix_fine_status", "tenant_id", "status"),
        {"extend_existing": True},
    )
    
    # Student
    student_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
    )
    
    # Fine details
    fine_type: Mapped[FineType] = mapped_column(
        SQLEnum(FineType, name="fine_type_enum"),
    )
    description: Mapped[str] = mapped_column(Text)
    
    # Amount
    amount: Mapped[Decimal] = mapped_column(Numeric(12, 2))
    paid_amount: Mapped[Decimal] = mapped_column(Numeric(12, 2), default=Decimal("0.00"))
    waived_amount: Mapped[Decimal] = mapped_column(Numeric(12, 2), default=Decimal("0.00"))
    balance: Mapped[Decimal] = mapped_column(Numeric(12, 2))
    
    # Status
    status: Mapped[FineStatus] = mapped_column(
        SQLEnum(FineStatus, name="fine_status_enum"),
        default=FineStatus.PENDING
    )
    
    # Dates
    imposed_on: Mapped[date] = mapped_column(Date)
    due_date: Mapped[Optional[date]] = mapped_column(Date, nullable=True)
    
    # Reference
    reference_type: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)  # invoice, library_book, etc.
    reference_id: Mapped[Optional[UUID]] = mapped_column(PGUUID(as_uuid=True), nullable=True)
    
    # Imposed by
    imposed_by: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
    )
    
    # Waiver
    waived_by: Mapped[Optional[UUID]] = mapped_column(
        PGUUID(as_uuid=True), nullable=True
    )
    waiver_reason: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    waiver_date: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )


# ============================================
# Fine Payment
# ============================================

class FinePayment(TenantBaseModel):
    """
    Payment against a fine.
    """
    __tablename__ = "fine_payments"
    __table_args__ = (
        Index("ix_fine_payment_fine", "fine_id"),
        {"extend_existing": True},
    )
    
    fine_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("fines.id", ondelete="CASCADE"),
    )
    
    amount: Mapped[Decimal] = mapped_column(Numeric(12, 2))
    payment_method: Mapped[str] = mapped_column(String(50))
    transaction_id: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    
    payment_date: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=datetime.utcnow
    )
    
    remarks: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    
    # Collected by
    collected_by: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
    )
