"""
CUSTOS Learning Schemas Init
"""

from app.learning.schemas.daily_loops import (
    MasteryLevel,
    DailySessionCreate,
    DailySessionResponse,
    DailySessionWithDetails,
    DailySessionWithQuestions,
    AttemptSubmit,
    AttemptBulkSubmit,
    AttemptResponse,
    AttemptWithFeedback,
    StudentMasteryResponse,
    MasteryWithDetails,
    StudentMasterySummary,
    StrongWeakQuestion,
    StrongWeakAnalysis,
    QuestionOption,
    QuestionForAttempt,
    TodaySessionInfo,
    DailyLoopStats,
)

from app.learning.schemas.weekly_tests import (
    WeeklyTestStatus,
    QuestionStrengthType,
    WeeklyTestCreate,
    WeeklyTestUpdate,
    WeeklyTestResponse,
    WeeklyTestWithDetails,
    WeeklyTestQuestionResponse,
    WeeklyTestQuestionWithContent,
    WeeklyTestPaper,
    WeeklyTestAnswerKey,
    StudentResultSubmit,
    BulkResultSubmit,
    WeeklyTestResultResponse,
    WeeklyTestResultWithDetails,
    WeeklyPerformanceResponse,
    StudentWeeklyHistory,
    GeneratePaperRequest,
    GeneratePaperResult,
    WeeklyTestStats,
)

__all__ = [
    # Daily Loops
    "MasteryLevel",
    "DailySessionCreate",
    "DailySessionResponse",
    "DailySessionWithDetails",
    "DailySessionWithQuestions",
    "AttemptSubmit",
    "AttemptBulkSubmit",
    "AttemptResponse",
    "AttemptWithFeedback",
    "StudentMasteryResponse",
    "MasteryWithDetails",
    "StudentMasterySummary",
    "StrongWeakQuestion",
    "StrongWeakAnalysis",
    "QuestionOption",
    "QuestionForAttempt",
    "TodaySessionInfo",
    "DailyLoopStats",
    # Weekly Tests
    "WeeklyTestStatus",
    "QuestionStrengthType",
    "WeeklyTestCreate",
    "WeeklyTestUpdate",
    "WeeklyTestResponse",
    "WeeklyTestWithDetails",
    "WeeklyTestQuestionResponse",
    "WeeklyTestQuestionWithContent",
    "WeeklyTestPaper",
    "WeeklyTestAnswerKey",
    "StudentResultSubmit",
    "BulkResultSubmit",
    "WeeklyTestResultResponse",
    "WeeklyTestResultWithDetails",
    "WeeklyPerformanceResponse",
    "StudentWeeklyHistory",
    "GeneratePaperRequest",
    "GeneratePaperResult",
    "WeeklyTestStats",
]
